### ISSUE TITLE
Changing the step size during evaluation

### ISSUE THREAD

**Issue by stefanwanckel** [PierreExeter/rl_reach#5]
I realized that my action step was too big and the robot was stuttering a lot.
So I reduced the action step and now I am not able to reach the goal within the maximum time steps (100).
I assume that my options would be to retrain the model with either a larger maximum time steps or to enlarge the action space.

I was wondering if I can scale the action space (or rather the step size) during evaluation without the need to retrain.

Thanks in advance for your help.

**Comment by stefanwanckel** [comment]
ADDENDUM: I can manually increase --n-eval-steps to >100 steps, but then the evaluation resets after 100 timesteps.

**Comment by PierreExeter** [comment]
The short answer is no. You should train and evaluate using the same environment. If you notice some oscillations at evaluation time, one solution is to increase the action space as you said by changing `action_min` and `action_max` in init.py. However you should then re-train.

Regarding your 2nd query, this is normal as the number of evaluation steps is independent of the `max_episode_steps=100` in init.py. However it makes sense to set `n-eval-steps` as a multiple of `max_episode_steps` to evaluate with a finite number of episode. For example, if `n-eval-steps = 2000` and  `max_episode_steps=100`, you will use 20 full episodes to evaluate your trained policy. However it makes sense to evaluate over many episodes mainly if you use non-deterministic evaluation.

**Comment by stefanwanckel** [comment]
Thanks for the thorough explanation. As a short follow-up: Where do the action_min and action_max from the init.py overwrite the hard-coded action_min and action max in the environment?

**Comment by PierreExeter** [comment]
action_min and action_max are used to define the boundaries of the action space [here](https://github.com/PierreExeter/rl_reach/blob/ef4c8031a404ea8af823444ada2bd5f8a736ef4c/code/gym_envs/widowx_env/envs/widowx_env.py#L111-L112)
